IF
	HasItem("ACQ16001","THALANTYR")
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FadeToColor([20.0],0)
		ActionOverride("THALANTYR",DestroyItem("ACQ16001"))
        	Wait(2)		
//		ActionOverride("THALANTYR",ForceSpell("THALANTYR",EFFECT_ONLY))
        	FadeFromColor([20.0],0)
		Wait(2)
		ActionOverride("THALANTYR",GiveItemCreate("ACQ16005",LastTalkedToBy(),0,0,0))
		DisplayStringHead("THALANTYR",@5010)
		Wait(2)	
		EndCutSceneMode()
END